# Generated by Django 5.2.6 on 2025-09-29 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car_Inventory',
            fields=[
                ('Plate_No', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Car_Model', models.CharField(max_length=100)),
                ('Car_Type', models.CharField(max_length=20)),
                ('Mileage', models.IntegerField()),
                ('Engine_Type', models.CharField(max_length=15)),
            ],
        ),
    ]
